version: '3'

services:
  node:
    build: ./docker/node
    ports:
      - 8094:3000
    volumes:
      - ./docker/node/sources:/trade-plus-api
    tty: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3.15-bionic
    container_name: trade-plus-mariadb
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13311:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trade_plus
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Singapore

#  prisma:
#    image: prismagraphql/prisma:1.34
#    restart: always
#    ports:
#      - '4466:4466'
#    environment:
#      PRISMA_CONFIG: |
#        port: 4466
#        databases:
#          default:
#            connector: mysql
#            host: mysql
#            port: 3306
#            user: root
#            password: prisma
#
#  mysql:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: prisma
#    volumes:
#      - mysql:/var/lib/mysql
#
#volumes:
#  mysql: ~